
   <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#campusNavDropdown" aria-controls="campusNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
   <span class="navbar-toggler-icon"></span>
   </button>
   <div class="collapse navbar-collapse" id="campusNavDropdown">
      <ul class="navbar-nav mr-auto mb-2 mb-lg-0">
         <!-- Mega Menu 1 -->
         <li class="nav-item dropdown dropdown-mega position-static">
            <a class="nav-link dropdown-toggle" href="https://broome-bs1.ddev.site/academics-programs/" role="button" data-bs-toggle="dropdown" aria-expanded="false">Academics &amp; Programs</a>
            <div class="dropdown-menu megamenu vw-100 start-50 mt-3 translate-middle-x" aria-labelledby="navbarDropdown">
               <div class="container">
                  <div class="row d-flex justify-content-center">
                        
                     <div class="col-md-3 px-3">
                        <p>The best way to know if SUNY Broome is right for you is to come visit!</p>
                    </div>
                     <ul class="col-md-3 px-5">
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/academics-programs/programs-courses/">Programs &amp; Courses</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/academics-programs/programs-courses/our-programs/">Our Programs</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/academics-programs/programs-courses/our-courses/">Our Courses</a></li>
                        <li><a class="dropdown-item" href="https://catalog.sunybroome.edu/">College Catalog</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/ffec/">Fast Forward &amp; Early College</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/international/study-abroad/">Global Experiences (Study Abroad)</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/microcreds/">Microcredentials</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/academics-programs/programs-courses/non-credit-courses/">Non-Credit Courses</a></li>
                     </ul>
                     <ul class="col-md-3 px-5">
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/academics-programs/academic-divisions/">Academic Divisions</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/divisions/bps/">Business &amp; Professional Studies</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/divisions/hs/">Health Sciences</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/divisions/la/">Liberal Arts</a></li>
                        <li><a class="dropdown-item text-wrap" href="https://broome-bs1.ddev.site/divisions/stem/">Science, Technology, Engineering &amp; Mathematics (STEM)</a></li>
                     </ul>
                     <ul class="col-md-3 px-5">
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/academics-programs/academic-resources/">Academic Resources</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/academicadvising/">Academic Advising</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/lad/">Learning Assistance Department</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/successcoaching/">Success Coaching</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/student-success-center-instructions/">Success Center Instructions</a></li>
                        <li><a class="dropdown-item" href="https://sunybroome.info/library/">Library</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/registrar/college-academic-calendar/">Academic Calendar</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/student-orientation/online-orientation/">Online Orientation</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/online/">Student Resources</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/eop/">Educational Opportunity Program (EOP)</a></li>
                     </ul>
                  </div>
                  <!--/row  -->
               </div>
               <!--/container red -->
            </div>
            <!-- Mega Menu 1 -->
         </li>
         <!-- Mega Menu 2 -->
         <li class="nav-item dropdown dropdown-mega position-static ">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Admissions &amp; Costs</a>
            <div class="dropdown-menu megamenu vw-100 start-50 translate-middle-x" aria-labelledby="navbarDropdown">
               <div class="container">
                  <div class="row d-flex justify-content-center">
                     <ul class="col-md-3 px-4">
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/apply/">Apply to SUNY Broome</a>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/ffec/">Fast Forward &amp; Early College</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/student-orientation/">Orientation</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/ask-a-question/">Request More Information</a></li>
                        <li><a class="dropdown-item bigfat-menu" href="https://broome-bs1.ddev.site/admissions-costs/parents-families/">Parents &amp; Families</a></li>
                     </ul>
                     <ul class="col-md-3 px-4">
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/admissions/">Admissions</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/admissions/admissions-requirements/">Admissions Requirements</a></li>
                        <li><a class="dropdown-item" href="http://connect.sunybroome.edu/portal/counselor">Admissions Counseling</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/admissions/inquire/">Ask a Question</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/admissions/enrollment-checklist/">Enrollment Checklist</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/admissions/admission-for-competitive-health-sciences-programs/">Competitive Admissions</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/international/">International Education</a></li>
                        <li><a class="dropdown-item" href="https://connect.sunybroome.edu/portal/groupvisits">Group Visits</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/admissions/suny-broome-on-the-move/">On the Move</a></li>
                     </ul>
                     <ul class="col-md-3 px-4">
                        <li><a class="dropdown-item" href="#awb-off-canvas-menu-trigger">Transfers</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/special-topics/transfer/">Transfer to SUNY Broome</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/transfer-planning/reverse-transfer/">Reverse Transfer</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/transfer-planning/bachelor-partnerships/">Bachelor Partnerships</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/transferagreements/">Transfer Agreements</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/transfer-planning/">Transfer Planning</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/admissions/broomes-suny-transfer-partnerships/">SUNY Transfer Partnerships</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/admissions/broome-2-binghamton-program/">Broome 2 Binghamton</a></li>
                     </ul>
                     <ul class="col-md-3 px-4">
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/admissions-costs/registration-payment/">Registration &amp; Payment</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/academicadvising/">Advising &amp; Registration</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/admissions-costs/registration-payment/course-registration-options/">Course Registration Options</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/financialaid/">Student Financial Services</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/registrar/">Registrar’s Office</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/financialaid/scholarships-grants-and-loans/">Scholarships, Grants and Loans</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/financialaid/student-accounts/">Student Accounts</a></li>
                     </ul>
                  </div>
                  <!--/row  -->
               </div>
               <!--/container-->
            </div>
            <!-- Mega Menu 2 -->
         </li>
         <!-- Mega Menu 3 -->
         <li class="nav-item dropdown dropdown-mega position-static ">
            <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false" href="https://broome-bs1.ddev.site/our-campus/">Our Campus</a>
            <div class="dropdown-menu megamenu vw-100 start-50 translate-middle-x" aria-labelledby="navbarDropdown">
               <div class="container">
                  <div class="row d-flex justify-content-center">
                     <ul class="col-md-3 px-4">
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/our-campus/student-activities-campus-life/">Student Activities &amp; Campus Life</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/housing/">Student Housing</a></li>
                        <li><a class="dropdown-item" href="https://broomehornets.com/landing/index">Athletics</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/special-topics/arts/">The Arts at SUNY Broome</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/dos/campus-life-office/">Campus Life Office</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/civic-engagement/">Civic Engagement</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/dos/">Dean of Students</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/diversity-inclusion/">Diversity &amp; Inclusion</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/icecenter/">Ice Center</a></li>
                        <li><a class="dropdown-item" href="https://sunybroome.campuslabs.com/engage/">The Swarm – Clubs &amp; Organizations</a></li>
                     </ul>
                     <ul class="col-md-3 px-4">
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/wellness/">Wellness</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/counseling/">Counseling Services</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/healthservices/">Health Services</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/safety/">Public Safety</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/titleix/">Title IX</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/financialaid/helpforhornets/">Help for Hornets</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/safety/policies-report/">Annual Safety and Security Report</a></li>
                     </ul>
                     <ul class="col-md-3 px-4">
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/our-campus/on-campus-services/">On-Campus Services</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/bccenter/">Child Care – The BC Center</a></li>
                        <li><a class="dropdown-item" href="https://sunybroome.bncollege.com/">Bookstore &amp; Campus Shop</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/our-campus/dining-at-suny-broome/">Campus Dining</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/fsa/">Faculty-Student Association</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/our-campus/on-campus-services/it-helpdesk/">IT/Helpdesk</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/veterans/">Veterans &amp; Military Affairs</a></li>
                     </ul>
                     <ul class="col-md-3 px-4">
                        <li><a class="dropdown-item" href="#awb-off-canvas-menu-trigger">Campus Policies &amp; Student Conduct</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/our-campus/academic-grievance-procedure/">Academic Grievance Procedure</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/osrr/student-code-of-conduct/">Student Code of Conduct</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/our-campus/complaints-grievances-appeals/">Student Complaints, Grievances, and Appeals</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/our-campus/civility-statement/">Civility Statement</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/wp-content/uploads/2025/03/Family-Education-Rights-and-Privacy-Act-FERPA.pdf">Educational Rights &amp; Privacy Act</a></li>
                        <li><a class="dropdown-item" href="#">Policies &amp; Prodecures</a></li>
                        <li><a class="dropdown-item" href="#">Student Handbook</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/wp-content/uploads/2025/03/4.4-Student-Rights-and-Responsibilities-Statement.pdf">Student Rights</a></li>
                     </ul>
                  </div>
                  <!--/row  -->
               </div>
               <!--/container-->
            </div>
            <!-- Mega Menu 3 -->
         </li>
         <!-- Mega Menu 4 -->
         <li class="nav-item dropdown dropdown-mega position-static ">
            <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false" href="https://broome-bs1.ddev.site/about/">About</a>
            <div class="dropdown-menu megamenu vw-100 start-50 translate-middle-x" aria-labelledby="navbarDropdown">
               <div class="container-fluid">
                  <div class="row d-flex justify-content-center">
                     <ul class="col-md-2 px-3">
                        <li><a class="dropdown-item" href="#">Our Institution</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/about/area-highlights/">Area Highlights</a></li>
                        <li><a class="dropdown-item" href="https://news.sunybroome.edu/buzz/">The Buzz – Campus News</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/about/college-history/">College History</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/about/directions-to-campus/">Directions to Campus</a></li>
                        <li><a class="dropdown-item" href="https://news.sunybroome.edu/calendar/events/">Events Calendar</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/about/on-campus-services/">On-Campus Services</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/housing/">Student Housing</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/about/map/">Parking and Campus Map</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/about/weather-related-closure-and-cancellation-procedure/">Weather-Related Closure and Cancellation Procedure</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/about/gatherings-and-assemblies-designated-public-areas/">Gatherings and Assemblies Designated Public Areas</a></li>
                     </ul>
                    <div class="col-md-2 px-3">
                         <ul class="mb-3">
                            <li><a class="dropdown-item" href="#">Our Vision &amp; Mission</a></li>
                            <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/about/vision/">Vision, Mission, Values and Institutional Learning Outcomes</a></li>
                            <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/wp-content/uploads/2025/03/Civility-Statement.pdf">Civility Statement</a></li>
                            <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/diversity-inclusion/">Diversity &amp; Inclusion</a></li>
                         </ul>
                         <ul>
                            <li><a class="dropdown-item" href="#">Our People &amp; Employment</a></li>
                            <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/shared-governance/chancellors-awards/">Chancellor’s Award Winners</a></li>
                            <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/about/employment/">Human Resources &amp; Employment</a></li>
                            <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/careercenter/student-employment-resources/">Student Employment Resources</a> </li>
                            <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/about/student-employment-job-posting-submission/">Student Employment Job Posting Submission</a></li>
                            <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/about/student-employment-vacancies/">Student Employment Vacancies</a></li>
                            <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/faculty-and-staff/spirit-award/">SUNY Broome Spirit Award</a></li>
                         </ul>
                       </div>
                     <ul class="col-md-2 px-3">
                        <li><a class="dropdown-item" href="#awb-off-canvas-menu-trigger">Information, Planning &amp; Reporting</a> </li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/about/annual-report/">Annual Report</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/about/consumer-information/">Consumer Information</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/about/fast-facts/">Enrollment Statistics (Fast Facts)</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/about/foil/">Freedom of Information Law (FOIL) Requests</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/ie/">Institutional Effectiveness</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/strategic-planning/">Strategic Planning</a></li>
                     </ul>
                     <ul class="col-md-2 px-3">
                        <li><a class="dropdown-item" href="#awb-off-canvas-menu-trigger">Governance &amp; Administration</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/bot/">Board of Trustees</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/about/office-of-the-president/">Office of The President</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/about/organizational-charts/">Organizational Charts</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/pp/">Policies &amp; Procedures</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/shared-governance/">Shared Governance</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/shared-governance/student-assembly/">Student Assembly</a></li>
                     </ul>
                     <ul class="col-md-2 px-3">
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/accessibility/">Accessibility</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/accessibility/digital-content/">Digital Content Accessibility</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/accessibility/classroom/">Classroom Accessibility</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/accessibility/web/">Web Accessibility</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/lad/aro/">Accessibility Resources</a></li>
                     </ul>
                  </div>
                  <!--/row  -->
               </div>
               <!--/container-->
            </div>
            <!-- Mega Menu 4 -->
         </li>
         <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="https://broome-bs1.ddev.site/careers-workforce/" role="button" data-bs-toggle="dropdown" aria-expanded="false">Careers &amp; Workforce</a>
            <ul class="dropdown-menu">
               <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/careers-workforce/conted/">Continuing Education</a></li>
               <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/careers-workforce/workforce-development/">Workforce Development</a></li>
               <li><a class="dropdown-item" href="https://ce.sunybroome.edu/">CE Course Catalog</a></li>
               <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/careercenter/">Career Services</a></li>
               <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/careercoach/">Career Coach</a> </li>
               <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/conted/eac/">Entrepreneurship Assistance</a></li>
               <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/careers-workforce/on-campus-jobs/">On-Campus Jobs</a></li>
               <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/conted/suny-apprenticeship/">Apprenticeships</a></li>
            </ul>
         </li>
         <!-- Mega Menu 5 -->
         <li class="nav-item dropdown dropdown-mega position-static ">
            <a class="nav-link dropdown-toggle"  role="button" data-bs-toggle="dropdown" aria-expanded="false" href="https://broome-bs1.ddev.site/community-alumni/">Foundation &amp; Alumni</a>
            <div class="dropdown-menu megamenu vw-100 start-50 translate-middle-x" aria-labelledby="navbarDropdown">
               <div class="container">
                  <div class="row d-flex justify-content-center">
                     <ul class="col-md-4 px-5">
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/community-alumni/give/">♥Give</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/foundation/whygive/">Why Give</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/foundation/waystogive/">Ways To Give</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/foundation/fscampaign/">Faculty and Staff Giving Campaign</a></li>
                        <li><a class="dropdown-item bigfat-menu" href="https://broome-bs1.ddev.site/community-alumni/suny-broome-scholarships/">SUNY Broome Scholarships</a></li>
                        <li><a class="dropdown-item bigfat-menu" href="https://broome-bs1.ddev.site/community-alumni/vip-employee-appreciation-campaign/">VIP Employee Appreciation Campaign</a></li>
                     </ul>
                     <ul class="col-md-4 px-5">
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/foundation/alumni/">Alumni &amp; Friends</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/foundation/update-your-information/">Update Your Information</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/foundation/class-note-submission-form/">Class Note Submission Form</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/foundation/broome/">BROOME Magazine</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/foundation/benefits/">Alumni Benefits</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/community-alumni/alumni-features/">Alumni Features</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/foundation/alumnievent/">Alumni Events</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/registrar/transcripts/">Request Transcript</a></li>
                     </ul>
                     <ul class="col-md-4 px-5">
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/community-alumni/suny-broome-foundation/">SUNY Broome Foundation</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/foundation/about/">About the Foundation</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/foundation/foundationstaff/">Foundation Staff</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/foundation/foundationboard/">Foundation Board of Directors</a></li>
                        <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/foundation/foundationreport/">Foundation Annual Report</a></li>
                     </ul>
                  </div>
                  <!--/row  -->
               </div>
               <!--/container-->
            </div>
            <!-- Mega Menu 5 -->
       <!--  <li><a class="nav-link" href="https://broome-bs1.ddev.site/apply/">Apply Now</a></li> -->
      </ul>
      <!-- /collapse -->
   </div>
   <!-- /container -->

</nav><!-- /campusnav -->

