<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#campusNavDropdown" aria-controls="campusNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
<span class="navbar-toggler-icon"></span>
</button>


   <div class="collapse navbar-collapse justify-content-end" id="campusNavDropdown">
      <ul class="navbar-nav mr-auto mb-2 mb-lg-0">
         <!-- Mega Menu 1 -->
         <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="https://broome1.wpenginepowered.com/academics-programs/" id="dropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">Academics &amp; Programs</a>
                      <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink"> 
                        <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/academics-programs/programs-courses/">Programs &amp; Courses</a></li>
                        <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/academics-programs/academic-divisions/">Academic Divisions</a></li>
                        <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/academics-programs/academic-resources/">Academic Resources</a></li>
                     </ul>
            <!-- Mega Menu 1 -->
         </li>
         <!-- Mega Menu 2 -->
         <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="https://broome1.wpenginepowered.com/admissions-costs/" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">Admissions &amp; Costs</a>
                     <ul  class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                        <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/apply/">Apply to SUNY Broome</a>
                        <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/admissions/">Admissions</a></li>
                        <li><a class="dropdown-item" href="#awb-off-canvas-menu-trigger">Transfers 404</a></li>
                        <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/admissions-costs/registration-payment/">Registration &amp; Payment</a></li>
                     </ul>
            <!-- Mega Menu 2 -->
         </li>
         <!-- Mega Menu 3 -->
         <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" id="dropdownMenuLink" aria-expanded="false" href="https://broome1.wpenginepowered.com/our-campus/">Our Campus</a>
                     <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                        <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/our-campus/student-activities-campus-life/">Student Activities &amp; Campus Life 404</a></li>
                        <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/wellness/">Wellness</a></li>
                        <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/our-campus/on-campus-services/">On-Campus Services</a></li>
                        <li><a class="dropdown-item" href="#awb-off-canvas-menu-trigger">Campus Policies &amp; Student Conduct</a></li>
                     </ul>
            <!-- Mega Menu 3 -->
         </li>
         <!-- Mega Menu 4 -->
         <li class="nav-item dropdown ">
            <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" id="dropdownMenuLink" aria-expanded="false" href="https://broome1.wpenginepowered.com/about/">About</a>
                          <ul  class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                <li><a class="dropdown-item" href="#">Our Institution</a></li>
                            <li><a class="dropdown-item" href="#">Our Vision &amp; Mission</a></li>
                            <li><a class="dropdown-item" href="#">Our People &amp; Employment</a></li>
                             <li><a class="dropdown-item" href="#awb-off-canvas-menu-trigger">Information, Planning &amp; Reporting</a> </li>
                             <li><a class="dropdown-item" href="#awb-off-canvas-menu-trigger">Governance &amp; Administration</a></li>
                             <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/accessibility/">Accessibility</a></li>
                     </ul>
            <!-- Mega Menu 4 -->
         </li>
         <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="https://broome1.wpenginepowered.com/careers-workforce/" id="dropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">Careers &amp; Workforce</a>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink"> 
               <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/careers-workforce/conted/">Continuing Education</a></li>
               <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/careers-workforce/workforce-development/">Workforce Development</a></li>
               <li><a class="dropdown-item" href="https://ce.sunybroome.edu/">CE Course Catalog</a></li>
               <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/careercenter/">Career Services</a></li>
               <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/careercoach/">Career Coach</a> </li>
               <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/conted/eac/">Entrepreneurship Assistance</a></li>
               <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/careers-workforce/on-campus-jobs/">On-Campus Jobs</a></li>
               <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/conted/suny-apprenticeship/">Apprenticeships</a></li>
            </ul>
         </li>
         <!-- Mega Menu 5 -->
         <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle"  role="button" data-bs-toggle="dropdown" id="dropdownMenuLink" aria-expanded="false" href="https://broome1.wpenginepowered.com/community-alumni/">Foundation &amp; Alumni</a>

                     <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                        <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/community-alumni/give/">♥Give</a></li>
                        <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/foundation/alumni/">Alumni &amp; Friends</a></li>
                        <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/community-alumni/suny-broome-foundation/">SUNY Broome Foundation</a></li>
                     </ul>
                </li>
            <!-- Mega Menu 5 -->
      <!--   <li><a class="nav-link" href="https://broome1.wpenginepowered.com/apply/">Apply Now</a></li> -->
      </ul>
      <!-- /collapse -->
   </div>
   <!-- /container -->
</nav><!-- /campusnav -->

