


<div class="region region-nav-search">
   <div id="block-psul-theme-popupsearchblock" class="block-psul-search block-psul-search-popup-search-block">
      <div class="dropdown">
         <button class="btn btn-link dropdown-toggler py-1 px-2" type="button" data-bs-toggle="dropdown" aria-expanded="false" data-bs-auto-close="outside">
         <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
  <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001q.044.06.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1 1 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0"/>
</svg>
<span class="visually-hidden"> Start Search</span>
         </button>
         <div class="dropdown-menu dropdown-menu-end p-2 p-md-3">

            <form class="psul-search-popup-search"  action="/" method="post" id="psul-search-popup-search" accept-charset="UTF-8">
               <div class="input-group input-group-sm js-form-wrapper form-wrapper" id="edit-options-container">
                  <span class="input-group-text">in:</span>
                  <select aria-label="Search within"  id="edit-search-options" name="search_options" class="form-select form-control">
                     <option value="library" selected="selected">Articles, Books, and More</option>
                     <option value="broome">SUNY Broome</option>
                  </select>
               </div><!-- / input group -->

               <div class="input-group js-form-wrapper form-wrapper"  id="edit-query-container">
                  <input placeholder="Search" maxlength="256" class="border-1 border-top-0 form-text form-control" aria-label="Search"  type="text" id="edit-query" name="query" value="" size="60" />

                  <button class="search-submit btn-square button js-form-submit form-submit btn btn-info"  type="submit" id="edit-submit" name="op" value="Search">
Search</button>
               </div><!-- /input group  -->

               <input autocomplete="off"  type="hidden" name="form_build_id" value="form-OU-vdBxJE3sptsPoTlFH5GPjX1XDXUNdJENw03jQoCw" />
               <input data-drupal-selector="edit-psul-search-popup-search" type="hidden" name="form_id" value="psul_search_popup_search" />

            <a href="https://suny-bcc.primo.exlibrisgroup.com/discovery/search?vid=01SUNY_BCC:01SUNY_BCC&lang=en">Search for articles and books instead</a>
            </form>
         </div><!-- /dropdown-menu  -->
         </div><!-- /dropdown  -->
      </div><!-- / popupsearchblock -->
   </div><!-- / region-nav-search -->


    <button class="navbar-toggler campusbutton" type="button" data-bs-toggle="offcanvas" data-bs-target="#campusNavDropdown" aria-controls="campusNavDropdown" aria-expanded="false" aria-label="Toggle navigation">              
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-list" viewBox="0 0 16 16">
              <path fill-rule="evenodd" d="M2.5 12a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5m0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5m0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5"/>
            </svg>
            <span class="icon-text">campus</span>
    </button>

</nav><!-- /container -->

</div><!-- secondnav-->
