<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#campusNavDropdown" aria-controls="campusNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
<span class="navbar-toggler-icon"></span>
</button>

   <div class="collapse navbar-collapse justify-content-end" id="campusNavDropdown">
      <ul class="navbar-nav mr-auto mb-2 mb-lg-0">
         <!-- Mega Menu 1 -->
         <li class="nav-item"><a class="nav-link" href="https://broome1.wpenginepowered.com/academics-programs/">Academics &amp; Programs</a></li>
         <li class="nav-item"><a class="nav-link" href="https://broome1.wpenginepowered.com/admissions-costs/">Admissions &amp; Costs</a></li>
         <li class="nav-item"><a class="nav-link" href="https://broome1.wpenginepowered.com/our-campus/">Our Campus</a></li>
         <li class="nav-item"><a class="nav-link" href="https://broome1.wpenginepowered.com/about/">About</a></li>
         <li class="nav-item"><a class="nav-link" href="https://broome1.wpenginepowered.com/careers-workforce/">Careers &amp; Workforce</a></li>
         <li class="nav-item"><a class="nav-link" href="https://broome1.wpenginepowered.com/community-alumni/">Foundation &amp; Alumni</a></li>
      <!--   <li class="nav-item"><a class="nav-link" href="https://broome1.wpenginepowered.com/apply/">Apply Now</a></li> -->
      </ul>
      <!-- /collapse -->
   </div>
   <!-- /container -->
</nav><!-- /campusnav -->

