<div class="secondnav">
<nav class="navbar campusnav bg-body-tertiary navbar-expand-xl">
   <div class="container">
   <div class="campus-logo">
      <a class="navbar-brand" href="https://sunybroome.edu"><img src="images/sunybroome-words_retina.png" alt="SUNY Broome Logo" height="27" width="250"></a> 
   </div>

<button class="navbar-toggler campusbutton" type="button" data-bs-toggle="offcanvas" data-bs-target="#campusNavDropdown" aria-controls="campusNavDropdown" aria-expanded="false" aria-label="Toggle navigation">              
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-list" viewBox="0 0 16 16">
          <path fill-rule="evenodd" d="M2.5 12a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5m0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5m0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5"/>
        </svg>
        <span class="icon-text">campus</span>
</button>

   <div class="offcanvas offcanvas-end" tabindex="-1" id="campusNavDropdown" aria-labelledby="campusNavDropdown">
            <div class="offcanvas-header">
              <h5 class="offcanvas-title" id="offcanvasNavbarDarkLabel">Campus Main Menu</h5>
              <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
            </div><!-- /header -->
   <div class="offcanvas-body">
      <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
         <li class="nav-item"><a class="nav-link" href="https://broome1.wpenginepowered.com/academics-programs/">Academics &amp; Programs</a></li>
         <li class="nav-item"><a class="nav-link" href="https://broome1.wpenginepowered.com/admissions-costs/">Admissions &amp; Costs</a></li>
         <li class="nav-item"><a class="nav-link" href="https://broome1.wpenginepowered.com/our-campus/">Our Campus</a></li>
         <li class="nav-item"><a class="nav-link" href="https://broome1.wpenginepowered.com/about/">About</a></li>
         <li class="nav-item"><a class="nav-link" href="https://broome1.wpenginepowered.com/careers-workforce/">Careers &amp; Workforce</a></li>
         <li class="nav-item"><a class="nav-link" href="https://broome1.wpenginepowered.com/community-alumni/">Foundation &amp; Alumni</a></li>
      <!--   <li class="nav-item"><a class="nav-link" href="https://broome1.wpenginepowered.com/apply/">Apply Now</a></li> -->
      </ul>
       </div><!-- /offcanvas -->
   </div><!-- /container -->
</nav><!-- /campusnav -->

