
			<h3>Quick Links</h3>
			<ul class="quicklinks">
				<li><a href="https://sunybroome.edu/lad/aro/">Accessibility Resources</a></li>
				<li><a href="https://sunybroome.edu/careercenter/">Career Services</a></li>
				<li><a href="https://sunybroome.edu/diversity/">Diversity & Inclusion</a></li>
				<li><a href="https://sunybroome.edu/icecenter/">Ice Center</a></li>
				<li class="last"><a href="https://sunybroome.info/library/">Library</a></li>
			</ul>	

				

       

