<section class="cankle clearfix">	
	<div class="cankle-container container">	 
	  <div class="row">
		<div class="col-sm col-md-6 col-lg-3">
            <div class="mx-4">
			<h3 class="broome-yellow"><a href="https://www1.sunybroome.edu/"  alt="SUNY Broome"><img class="img-fluid" src="images/footerlogo.png"></a></h3>

				<p> 907 Front Street <br />Binghamton, NY 13905</p>
			<ul>
				<li><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-map-fill" viewBox="0 0 16 16">
  <path fill-rule="evenodd" d="M16 .5a.5.5 0 0 0-.598-.49L10.5.99 5.598.01a.5.5 0 0 0-.196 0l-5 1A.5.5 0 0 0 0 1.5v14a.5.5 0 0 0 .598.49l4.902-.98 4.902.98a.5.5 0 0 0 .196 0l5-1A.5.5 0 0 0 16 14.5zM5 14.09V1.11l.5-.1.5.1v12.98l-.402-.08a.5.5 0 0 0-.196 0zm5 .8V1.91l.402.08a.5.5 0 0 0 .196 0L11 1.91v12.98l-.5.1z"/>
</svg> <a href="https://broome1.wpenginepowered.com/broome/map/">Parking & Campus Map</a></li>
				<li><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-telephone-fill" viewBox="0 0 16 16">
  <path fill-rule="evenodd" d="M1.885.511a1.745 1.745 0 0 1 2.61.163L6.29 2.98c.329.423.445.974.315 1.494l-.547 2.19a.68.68 0 0 0 .178.643l2.457 2.457a.68.68 0 0 0 .644.178l2.189-.547a1.75 1.75 0 0 1 1.494.315l2.306 1.794c.829.645.905 1.87.163 2.611l-1.034 1.034c-.74.74-1.846 1.065-2.877.702a18.6 18.6 0 0 1-7.01-4.42 18.6 18.6 0 0 1-4.42-7.009c-.362-1.03-.037-2.137.703-2.877z"/>
</svg> Phone: <a href="tel:6077785000">607-778-5000</a></li>
				<li><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-envelope-fill" viewBox="0 0 16 16">
  <path d="M.05 3.555A2 2 0 0 1 2 2h12a2 2 0 0 1 1.95 1.555L8 8.414zM0 4.697v7.104l5.803-3.558zM6.761 8.83l-6.57 4.027A2 2 0 0 0 2 14h12a2 2 0 0 0 1.808-1.144l-6.57-4.027L8 9.586zm3.436-.586L16 11.801V4.697z"/>
</svg> <a href="https://sunybroome.edu/contact-us/">Contact Us</a></li>
		</ul>
        </div><!--mx-4 -->
		</div><!-- col-md-3-->


		<div class="col-sm col-md-6 col-lg-3">
            <div class="mx-4">
        <h3>Apply and Register</h3>
            <ul class="apply">
                <li><a href="https://catalog.sunybroome.edu/content.php?catoid=1&amp;navoid=77">Academic Calendar</a></li>
                <li><a href="https://sunybroome.edu/apply/">Apply to SUNY Broome</a></li>
                <li><a href="https://sunybroome.edu/our-programs/">Our Programs</a></li>
                <li><a href="https://sunybroome.edu/academics-programs/programs-courses/our-courses/">Course Options</a></li>
                <li class="last"><a href="https://sunybroome.edu/financialaid/">Student Financial Services</a></li>
            </ul>	
        </div><!--mx-4 -->
		</div><!--col-md-3 -->

		<div class="col-6 col-lg-3">
            <div class="mx-4">
			<h3>Quick Links</h3>
			<ul class="quicklinks">
				<li><a href="https://sunybroome.edu/lad/aro/">Accessibility Resources</a></li>
				<li><a href="https://sunybroome.edu/careercenter/">Career Services</a></li>
				<li><a href="https://sunybroome.edu/diversity/">Diversity & Inclusion</a></li>
				<li><a href="https://sunybroome.edu/icecenter/">Ice Center</a></li>
				<li class="last"><a href="https://sunybroome.info/library/">Library</a></li>
			</ul>	
        </div><!--mx-4 -->
		</div><!--col-md-3 -->

		<div class="col-6 col-lg-3">
            <div class="mx-4">
			<h3>Health & Safety</h3>
			<ul class="health">
				<li><a href="https://sunybroome.edu/healthservices/">Health Services</a></li>
				<li><a href="https://sunybroome.edu/safety/">Public Safety</a></li>
				<li class="last"><a href="https://sunybroome.edu/titleix/">TitleIX</a></li>
			</ul>
        </div><!--mx-4 -->
			</div> <!-- col-md-3 -->
		</div><!-- row -->
	</div><!-- container -->	
</section>
				

       

