<section class="cankle clearfix">	
	<div class="container">	 
	  <div class="row">
		<div class="col-md-3">
			<h3 class="broome-yellow"><a href="https://www1.sunybroome.edu/">SUNY Broome</a></h3>

				<p> 907 Front Street <br />Binghamton, NY 13905</p>
			<ul>
				<li><a href="https://broome1.wpenginepowered.com/broome/map/">Parking & Campus Map</a></li>
				<li>Phone: <a href="tel:6077785000">607-778-5000</a></li>
				<li><a href="tel:6077785043">Contact Us</a></li>
		</ul>
		</div><!-- col-md-3-->


		<div class="col-md-3">
        <h3>Apply and Register</h3>
            <ul>
                <li><a href="https://catalog.sunybroome.edu/content.php?catoid=1&amp;navoid=77">Academic Calendar</a></li>
                <li><a href="https://broome1.wpenginepowered.com/apply/">Apply to SUNY Broome</a></li>
                <li><a href="https://broome1.wpenginepowered.com/academics-programs/programs-courses/">Programs &amp; Courses</a></li>
                <li><a href="https://broome1.wpenginepowered.com/financialaid/">Student Financial Services</a></li>
                <li><a href="https://broome1.wpenginepowered.com/admissions-costs/registration-payment/course-registration-options/">Course Registration Options</a></li>
                <li><a href="https://broome1.wpenginepowered.com/academics-programs/programs-courses/non-credit-courses/">Non-Credit Courses</a></li>
                <li><a href="https://broome1.wpenginepowered.com/special-topics/transfer/">Transferring to SUNY Broome</a></li>
            </ul>	
		</div><!--col-md-3 -->

		<div class="col-md-3">
			<h3>Quick Links</h3>
			<ul>
				<li><a href="https://broome1.wpenginepowered.com/lad/aro/">Accessibility Resources</a></li>
				<li><a href="https://broome1.wpenginepowered.com/careercenter/">Career Services</a></li>
				<li><a href="https://broome1.wpenginepowered.com/diversity/">Diversity & Inclusion</a></li>
				<li><a href="https://broome1.wpenginepowered.com/icecenter/">Ice Center</a></li>
				<li><a href="https://sunybroome.edu/library">Library</a></li>
			</ul>	
		</div><!--col-md-3 -->

		<div class="col-md-3">
			<h3><a href="https://www1.sunybroome.edu/" target="_blank">Health & Safety</a></h3>
			<ul>
				<li><a href="https://broome1.wpenginepowered.com/healthservices/">Health Services</a></li>
				<li><a href="https://broome1.wpenginepowered.com/safety/">Public Safety</a></li>
				<li><a href="https://broome1.wpenginepowered.com/titleix/">TitleIX</a></li>
			</ul>
			</div> <!-- col-md-3 -->
		</div><!-- row -->
	</div><!-- container -->	
</section>
				
           

