        <h3>Apply and Register</h3>
            <ul class="apply">
                <li><a href="https://catalog.sunybroome.edu/content.php?catoid=1&amp;navoid=77">Academic Calendar</a></li>
                <li><a href="https://sunybroome.edu/apply/">Apply to SUNY Broome</a></li>
                <li><a href="https://sunybroome.edu/our-programs/">Our Programs</a></li>
                <li><a href="https://sunybroome.edu/academics-programs/programs-courses/our-courses/">Course Options</a></li>
                <li class="last"><a href="https://sunybroome.edu/financialaid/">Student Financial Services</a></li>
            </ul>	

				

       

