<section class="cankle clearfix">	
	<div class="container">	 
	  <div class="row">
		<div class="col-md-3">
			<h3 class="broome-yellow"><a href="https://www1.sunybroome.edu/" >SUNY Broome</a></h3>
			<ul>
				<li> 
				<a href="https://www.google.com/maps/dir/42.3624704,-75.9496704/suny+broome+tyrell+library/@42.2447825,-76.0348665,11z/data=!3m1!4b1!4m9!4m8!1m1!4e1!1m5!1m1!1s0x89daef8ae64bddb1:0x87dabad1b642eda0!2m2!1d-75.9077496!2d42.1351353" target="_blank">907 Front Street, Binghamton, NY 13905</a></li>

				<li>Phone: <a href="tel:6077785000">607-778-5000</a></li>
				<li><a href="tel:6077785043">Contact Us</a></li>
		</ul>
		</div><!-- col-md-3-->


		<div class="col-md-3">
        <h3>Apply and Register</h3>
            <ul>
                <li><a href="https://catalog.sunybroome.edu/content.php?catoid=1&amp;navoid=77">Academic Calendar</a>
                </li>
                <li><a href="https://broome-bs1.ddev.site/apply/">Apply to SUNY Broome</a>
                </li>
                <li><a href="https://broome-bs1.ddev.site/academics-programs/programs-courses/">Programs &amp; Courses</a>
                </li>
                <li><a href="https://broome-bs1.ddev.site/financialaid/">Student Financial Services</a>
                </li>
                <li><a href="https://broome-bs1.ddev.site/admissions-costs/registration-payment/course-registration-options/">Course Registration Options</a>
                </li>
                <li><a href="https://broome-bs1.ddev.site/academics-programs/programs-courses/non-credit-courses/">Non-Credit Courses</a>
                </li>
                <li><a href="https://broome-bs1.ddev.site/special-topics/transfer/">Transferring to SUNY Broome</a>
                </li>
            </ul>	
		</div><!--col-md-3 -->

		<div class="col-md-3">
			<h3>Quick Links</h3>
			<ul>
				<li><a href="tel:6077785043">Accessibility Resources</a></li>
				<li><a href="/library/help">Career Services</a></li>
				<li><a href="/library/book-librarian">Diversity & Inclusion</a></li>
				<li><a href="mailto:reference@sunybroome.edu">Ice Center</a></li>
				<li><a href="/library/book-librarian">Library</a></li>
			</ul>	
		</div><!--col-md-3 -->

		<div class="col-md-3">
			<h3><a href="https://www1.sunybroome.edu/" target="_blank">Health & Safety</a></h3>
			<ul>
				<li><a href="https://broome1.wpenginepowered.com/healthservices/">Health Services</a></li>
				<li><a href="https://www.bkstr.com/sunybroomeccstore/home">Public Safety</a></li>
				<li><a href="https://www1.sunybroome.edu/about/map/">TitleIX</a></li>
			</ul>
			</div> <!-- col-md-3 -->
		</div><!-- row -->
	</div><!-- container -->	
</section>
				
           

