<style>
/* LibChat Widget CSS */
        #libchat_22a47fc81a2156a3037d58b5784f5fbb img { width: auto; height: auto; }
        #libchat_22a47fc81a2156a3037d58b5784f5fbb button { display: inline-block; padding: 6px 12px; margin-bottom: 0; text-align: center; white-space: nowrap; vertical-align: middle; cursor: pointer; background-image: none; border: 1px solid transparent; border-radius: 4px; background-color: #356ED7; color: #FAFAFA; }
        #libchat_22a47fc81a2156a3037d58b5784f5fbb button.libchat_online { background-color: #356ED7; color: #FAFAFA; }
        #libchat_22a47fc81a2156a3037d58b5784f5fbb button.libchat_bot { background-color: ; color: ; }

        /* overlay for modal */
        div[data-a11y-dialog-hide] { position: fixed; background-color: rgb(0, 0, 0); top: 0; left: 0; bottom: 0; right: 0; opacity: 0.3; z-index: 500; }
        /* modal */
        #libchat_modal_28113{ position: fixed; top: 0; left: 0; bottom: 0; right: 0; font-size: 100%; }
        #libchat_modal_28113[aria-hidden="true"] { display: none; }
        #libchat_modal_28113[data-a11y-dialog-native] > :first-child { display: none; }
        #libchat_modal_28113 div[role=document].dialog { position: relative; z-index: 501; margin: 50px auto; width: 300px; background-color: #F9F9F9; padding: 1em; border-radius: 5px; }
        /* modal content */
        #libchat_modal_28113 h1 { color: #3278E0; font-size: 2em; margin: 0 0 0.5em 0; padding: 0; line-height: 1.2em; }
        #libchat_modal_28113 button { color: #FFFFFF; background-color: #3278E0; margin: 1em 1em 0 0; border: none; border-radius: 5px; padding: 0.5em 1em; font-size: 1em; }

</style>

<div id="sul_chat_container">
<script src="https://sunybroome.libanswers.com/load_chat.php?hash=22a47fc81a2156a3037d58b5784f5fbb"></script>
<div class="askdt" id="libchat_22a47fc81a2156a3037d58b5784f5fbb"></div>
</div>


<div class="footerfooter">	 
	<div class="container-fluid">	
	<p>© 2024 - 2025 SUNY Broome Community College. All Rights Reserved. <a href="/library/accessibility">Accessibilty</a> | <a href="/library/comments">Comments</a> | <a href="http://www1.sunybroome.edu/terms-and-usage/privacy-guidelines/">Privacy Policy</a></p>	
</div>
</div>
