<!doctype html>
<html lang="en" data-bs-theme="auto">
   <head>
      <title>Bootstrap Library</title>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <link rel="preconnect" href="https://fonts.googleapis.com">
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
      <link href="https://fonts.googleapis.com/css2?family=Barlow+Semi+Condensed:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Roboto+Slab:wght@100..900&display=swap" rel="stylesheet">
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
      <script src="js/primo.js"></script>
      <link rel="stylesheet" href="css/style.css">

    <script defer data-domain="very.inept.quest" src="https://implausible.info/js/script.outbound-links.js"></script>
    <script>window.plausible = window.plausible || function() { (window.plausible.q = window.plausible.q || []).push(arguments) }</script>

   </head>
   <body>
      <div id="social-header">
         <div class="campus-links">
            <nav class="navbar bg-dark border-bottom border-body navbar-expand-lg" data-bs-theme="dark">
               <div class="container-fluid">
                  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#campuslinksNavDropdown" aria-controls="campuslinksNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                  </button>
                  <div class="collapse navbar-collapse" id="campuslinksNavDropdown">
                     <ul class="navbar-nav">
                        <li class="nav-item"><a class="nav-link" href="https://broome-bs1.ddev.site/directory/">Directory</a></li>
                        <li class="nav-item"><a class="nav-link" href="https://broome-bs1.ddev.site/faculty-and-staff/">Faculty &amp; Staff</a></li>
                        <li class="nav-item"><a class="nav-link" href="https://broome-bs1.ddev.site/community-business/">Community &amp; Business</a></li>
                        <li class="nav-item dropdown">
                           <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                           Calendar</a>
                           <ul class="dropdown-menu">
                              <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/calendar/">Calendar</a> </li>
                              <li><a class="dropdown-item" href="https://news.sunybroome.edu/calendar/events/list/?tribe_eventcategory%5B0%5D=317">Academic Calendar</a></li>
                              <li><a class="dropdown-item" href="https://news.sunybroome.edu/calendar/events/">Events Calendar</a></li>
                              <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/registrar/college-academic-calendar/">Key Dates</a></li>
                           </ul>
                        </li>
                        <li class="nav-item dropdown">
                           <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                           News</a>
                           <ul class="dropdown-menu">
                              <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/news/">News</a> </li>
                              <li><a class="dropdown-item" href="https://news.sunybroome.edu/buzz/">Buzz</a></li>
                              <li><a class="dropdown-item" href="https://news.sunybroome.edu/buzz/category/hivehq/">HiveHQ</a></li>
                           </ul>
                        </li>
                        <li class="nav-item dropdown">
                           <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                           Login</a>
                           <ul class="dropdown-menu">
                              <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/login/">Login</a></li>
                              <li><a class="dropdown-item" href="https://mycollege.sunybroome.edu">MyCollege</a></li>
                              <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/login/brightspace/">Brightspace</a></li>
                           </ul>
                        </li>
                        <li class="nav-item"><a class="nav-link" href="https://broome-bs1.ddev.site/community-alumni/give/">♥Give</a></li>
                     </ul>
                  </div>
                  <!-- /collapse -->
               </div>
               <!-- /container -->
            </nav>
         </div>
         <!-- /campus-links -->
      </div>
      <!-- /social-header -->
