<div id="contentbottom-wrapper">
<div class="row">
<div class="col-md-4">
	<section class="block-menu  panel panel-broome">
	      <h3 class="block-title">Find</h3>    
		 <ul class="nav flex-column">
			 <li class="nav-item"><a href="/library/databases" title="">Articles by Subject</a></li>
			 <li class="nav-item"><a href="/library/books-and-media" title="">Books and Media</a></li>
			 <li class="nav-item"><a href="/library/databases-by-title" title="">Database A-Z</a></li>
			 <li class="nav-item"><a href="/library/journals-and-magazines" title="">Journal A-Z </a></li>
		</ul>
	</section>

</div><!--col-md-3-->

<div class="col-md-4">
	<section class="block-menu  panel panel-broome">
			  <h3 class="block-title">Library Guides</h3>

	  <ul class="nav flex-column">
    <li class="first leaf"><a href="/library/guides/apa-style-guide">APA Style Guide</a></li>
	<li class="leaf"><a href="/library/guides/mla-style-guide">MLA Style Guide</a></li>
	<li class="leaf"><a href="/library/guides/chicago-manual-style-guidetemplate">Chicago Style Template</a></li>
	<li class="leaf"><a href="/library/course-guides" title="A library resource for students that contains handouts from library classes">Course Guides</a></li>
	<li class="leaf"><a href="/library/subject-guides" title="Guides to get you started researching a topic">Subject Guides</a></li>
	<li class="last leaf"><a href="/library/tutorials" title="">Tutorials</a></li>
	</ul>
	</section>
</div><!--col-md-5-->

<div class="col-md-4">
	<section class="block-menu panel panel-broome">
	       <h3 class="block-title">Services</h3>
    
	  <ul class="nav flex-column">
	<li class="leaf"><a href="/library/book-librarian" title="">Book a Librarian</a></li>
	<li class="leaf"><a href="/library/faculty-support" title="">Faculty Support</a></li>
	<li class="leaf"><a href="/library/interlibrary-loan" title="">Interlibrary Loan</a></li>
	<li class="leaf"><a href="/library/purchase-request" title="">Purchase Request</a></li>
	<li class="leaf"><a href="/library/reserve-study-room" title="">Reserve a Study Room</a></li>
	<li class="leaf"><a href="/library/textbooks-reserve" title="Textbooks and articles on Reserve">Textbooks on Reserve</a></li>
	<li class="last leaf"><a href="/library/accounts" title="">Your Library Accounts</a></li>
	</ul>
</section>
</div><!--col-md-4-->
			
			
	</div><!--row-->		
</div><!-- contentbottom-wrapper -->			
