    <script type="text/javascript" src="//lgapi-us.libapps.com/web/jquery/js/1.12.4_jquery.min.js"></script>
    <!-- js_include_fallback_lg.twig -->
<script src="//code.jquery.com/ui/1.13.2/jquery-ui.min.js"></script>
<script>1 || document.write('<script src="//lgapi-us.libapps.com/web/jquery/js/jquery-ui.min.js?2691">\x3C/script>');</script>
<!-- !js_include_fallback_lg.twig -->
<script type="text/javascript" src="//lgapi-us.libapps.com/web/bootstrap/3.4.1/js/bootstrap.min.js"></script>
<script type="text/javascript" src="//lgapi-us.libapps.com/web/js3.19.5/springshare.public.min.js"></script>
<script type="text/javascript" src="//lgapi-us.libapps.com/web/js3.19.5/springshare.common.min.js"></script>
<script type="text/javascript" src="//lgapi-us.libapps.com/web/js3.19.5/common/springspace_sui_helptip.js"></script>
<link rel="stylesheet" href="//lgapi-us.libapps.com/web/jquery/css/jquery-ui.min.css?2691"/>


<link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"/>
<link href="//lgapi-us.libapps.com/web/css3.19.5/common/springspace_sui_helptip.css" rel="stylesheet">

<script>
    var springStats = springStats || {};
    springStats.saConfig = springStats.saConfig || {
        site_id: 16957,
        tracking_parameters: {"_st_site_id":16957},
        tracking_server_host: "libguides-proc.springyaws.com"
    };
</script>
<script  src="//lgapi-us.libapps.com/web/js/sa.min.js?3116"></script>


<script>
    springSpace.Common = springSpace.Common || {};
    springSpace.Common.constant = {PROCESSING: {ACTION_DISPLAY_POLL: 159 }};
    springSpace.Common.baseURL = "//lgapi-us.libapps.com'/";
    springSpace.Common.apiLoad = true;
</script>
<script>springshare_widget_config_1755728872820 = { path: 'boxes/34834866', link_text: 'Content Box' };</script><div id="s-lg-widget-1755728872820"></div><script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://lgapi-us.libapps.com/widgets.php?site_id=16957&widget_type=8&output_format=1&widget_title=Research+Guides&widget_height=250&widget_width=100%25&widget_embed_type=1&guide_id=943257&box_id=34834866&map_id=40978371&content_only=0&include_jquery=1&config_id=1755728872820";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","s-lg-widget-script-1755728872820");</script>
