
<div class="homepagesearch tabs">

<ul class="nav flex-column nav-tabs flex-sm-row" role="tablist">
	<li class="nav-item"><a class="nav-link active" href="#tab-1" data-bs-toggle="tab">Subject Guides</a></li>
	<li class="nav-item"><a class="nav-link" href="#tab-2" data-bs-toggle="tab">Course Guides</a></li>
	<li class="nav-item"><a class="nav-link" href="#tab-3" data-bs-toggle="tab">How To Guides</a></li>
	<li class="nav-item"><a class="nav-link" href="#tab-4" data-bs-toggle="tab">Topic Guides</a></li>
	<li class="nav-item"><a class="nav-link" href="#tab-5" data-bs-toggle="tab">Other Guides</a></li>
</ul>	


<div class="tab-content border border-top-0">

	<div id="tab-1" class="tab-pane fade active show">


<script>springshare_widget_config_1755793091472 = { path: 'guides', link_text: 'Guides' };</script><div id="s-lg-widget-1755793091472"></div><script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://lgapi-us.libapps.com/widgets.php?site_id=16957&widget_type=1&search_terms=&search_match=2&sort_by=name&list_format=1&drop_text=Select+a+Guide...&output_format=1&load_type=2&enable_description=0&enable_group_search_limit=0&enable_subject_search_limit=0&guide_types%5B0%5D=3&widget_title=Guide+List&widget_height=250&widget_width=100%25&widget_link_color=2954d1&widget_embed_type=1&num_results=0&enable_more_results=0&window_target=2&config_id=1755793091472";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","s-lg-widget-script-1755793091472");</script>


	
	</div> <!-- tab-1 --> 


<div id="tab-2" class="tab-pane fade show">	
			
<script>springshare_widget_config_1755793180925 = { path: 'guides', link_text: 'Guides' };</script><div id="s-lg-widget-1755793180925"></div><script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://lgapi-us.libapps.com/widgets.php?site_id=16957&widget_type=1&search_terms=&search_match=2&sort_by=name&list_format=1&drop_text=Select+a+Guide...&output_format=1&load_type=2&enable_description=0&enable_group_search_limit=0&enable_subject_search_limit=0&guide_types%5B0%5D=2&widget_title=Guide+List&widget_height=250&widget_width=100%25&widget_link_color=2954d1&widget_embed_type=1&num_results=0&enable_more_results=0&window_target=2&config_id=1755793180925";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","s-lg-widget-script-1755793180925");</script>
		
	</div><!-- tab-2-->
	
	<div id="tab-3" class="tab-pane fade show">
<script>springshare_widget_config_1755793238705 = { path: 'guides', link_text: 'Guides' };</script><div id="s-lg-widget-1755793238705"></div><script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://lgapi-us.libapps.com/widgets.php?site_id=16957&widget_type=1&search_terms=&search_match=2&sort_by=name&list_format=1&drop_text=Select+a+Guide...&output_format=1&load_type=2&enable_description=0&enable_group_search_limit=0&enable_subject_search_limit=0&guide_types=&tag_ids%5B0%5D=724836&widget_title=Guide+List&widget_height=250&widget_width=100%25&widget_link_color=2954d1&widget_embed_type=1&num_results=0&enable_more_results=0&window_target=2&config_id=1755793238705";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","s-lg-widget-script-1755793238705");</script>
	</div><!-- tab-3-->
		
	<div id="tab-4" class="tab-pane fade show">
			<script>springshare_widget_config_1755793406505 = { path: 'guides', link_text: 'Guides' };</script><div id="s-lg-widget-1755793406505"></div><script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://lgapi-us.libapps.com/widgets.php?site_id=16957&widget_type=1&search_terms=&search_match=2&sort_by=name&list_format=1&drop_text=Select+a+Guide...&output_format=1&load_type=2&enable_description=0&enable_group_search_limit=0&enable_subject_search_limit=0&guide_types%5B0%5D=4&tag_ids=&widget_title=Guide+List&widget_height=250&widget_width=100%25&widget_link_color=2954d1&widget_embed_type=1&num_results=0&enable_more_results=0&window_target=2&config_id=1755793406505";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","s-lg-widget-script-1755793406505");</script>		

	</div><!--tab-4 -->
	
	
	<div id="tab-5" class="tab-pane fade show">
					<script>springshare_widget_config_1755793269143 = { path: 'guides', link_text: 'Guides' };</script><div id="s-lg-widget-1755793269143"></div><script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://lgapi-us.libapps.com/widgets.php?site_id=16957&widget_type=1&search_terms=&search_match=2&sort_by=name&list_format=1&drop_text=Select+a+Guide...&output_format=1&load_type=2&enable_description=0&enable_group_search_limit=0&enable_subject_search_limit=0&guide_types%5B0%5D=1&tag_ids=&widget_title=Guide+List&widget_height=250&widget_width=100%25&widget_link_color=2954d1&widget_embed_type=1&num_results=0&enable_more_results=0&window_target=2&config_id=1755793269143";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","s-lg-widget-script-1755793269143");</script>
	</div><!-- tab 5-->
	
</div><!-- tab-content -->

</div><!-- homepagesearch tabs -->
