			<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#libNavDropdown" aria-controls="#libNavDropdown"  aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
			</button>

				<div class="navbar-collapse collapse" id="libNavDropdown">
					<ul class="navbar-nav">
						<li class="nav-item dropdown">
							<a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false" href="about-library.php" title="">About Us<span class="caret"></span></a>
							<ul class="dropdown-menu">
								<li><a class="dropdown-item" href="about-library.php">About Us</a></li>
								<li><a class="dropdown-item" href="newbooks.php">New Books</a></li>
								<li><a class="dropdown-item" href="typography.php">Typography</a></li>
								<li><a class="dropdown-item" href="#">Databases by Subject</a></li>
								<li><a class="dropdown-item" href="primo.php">Primo</a></li>
								<li><a class="dropdown-item" href="journalaz.php">Journal A-Z</a></li>
								<li><a class="dropdown-item" href="grid.php">Grid</a></li>
							</ul>
						</li>
						<li class="nav-item dropdown">
							<a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false" href="about-library.php" title="">Find & Borrow<span class="caret"></span></a>   
							<ul class="dropdown-menu">
								<li><a class="dropdown-item" href="/library/databases" title="">Articles by Subject</a></li>
								<li><a class="dropdown-item" href="/library/books-and-media" title="">Books and Media</a></li>
								<li><a class="dropdown-item" href="/library/databases-by-title" title="">Database A-Z</a></li>
								<li><a class="dropdown-item" href="/library/interlibrary-loan" title="">Interlibrary Loan</a></li>
								<li><a class="dropdown-item" href="/library/journals-and-magazines" title="">Journal A-Z </a></li>
							</ul>
						</li>
						<li class="nav-item dropdown">
							<a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false" href="research-tools.php" title="">Library Guides<span class="caret"></span></a>
							<ul class="dropdown-menu">
								<li><a class="dropdown-item" href="#">APA Style Guide</a></li>
								<li><a class="dropdown-item" href="#">MLA Style Guide</a></li>
								<li><a class="dropdown-item" href="#">Chicago Style Template</a></li>
								<li><a class="dropdown-item" href="#">Course Guides</a></li>
								<li><a class="dropdown-item" href="#">Subject Guides</a></li>
							</ul>
						<li class="nav-item"><a class="nav-link" href="news-and-events.php">News & Events</a></li>

						
						<li class="nav-item dropdown">
							<a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false" href="about-library.php" title="">Services<span class="caret"></span></a>  
							<ul class="dropdown-menu">
								<li><a class="dropdown-item" href="/library/book-librarian" title="">Book a Librarian</a></li>
								<li><a class="dropdown-item" href="/library/faculty-support" title="">Faculty Support</a></li>
						        <li><a class="dropdown-item" href="oer/oer-home.php" title="Open Educational Resources">OER </a></li>
								<li><a class="dropdown-item" href="/library/interlibrary-loan" title="">Interlibrary Loan</a></li>
								<li><a class="dropdown-item" href="/library/purchase-request" title="">Purchase Request</a></li>
								<li><a class="dropdown-item" href="/library/reserve-study-room" title="">Reserve a Study Room</a></li>
								<li><a class="dropdown-item" href="/library/textbooks-reserve" title="Textbooks and articles on Reserve">Textbooks on Reserve</a></li>
								<li><a class="dropdown-item" href="/library/accounts" title="">Your Library Accounts</a></li>
							</ul>
						</li>
						<li class="nav-item"><a class="nav-link" href="help.php">Need Help?</a></li>
						<li class="nav-item"><a class="nav-link" href="index.php">V1</a></li>
						<li class="nav-item"><a class="nav-link" href="indexv2.php">V2</a></li>
					</ul>
				</div><!-- /navbar -->

</div><!-- /container -->
</div><!-- /thirdnav -->
</nav>

