<div id="front-display" class="container">
	<div class="row">	
		<div id="books-wrapper" class="col-md-7">
			<div class="books-display">
				<div class="region region-books-display">
				<h3 class="block-title">New Books</h3>
			        <div class="item-list">    
						<ul class="list-inline">          
							<li class="list-inline-item">  
					    <div class="views-field views-field-description">        <span class="field-content"><a href="https://suny-bcc.primo.exlibrisgroup.com/discovery/fulldisplay?docid=alma992265269704811&amp;context=U&amp;vid=01SUNY_BCC:01SUNY_BCC&amp;lang=en"><img class="book_cover" alt=" the authoritative medical guide for patients, families, doctors, and therapists by Bisaga, Adam" src="https://syndetics.com/index.php?client=primo&amp;isbn=1615194592/mc.jpg" /></a></span>  </div></li>
					            <li class="list-inline-item">  
					    <div class="views-field views-field-description">        <span class="field-content"><a href="https://suny-bcc.primo.exlibrisgroup.com/discovery/fulldisplay?docid=alma992265269804811&amp;context=U&amp;vid=01SUNY_BCC:01SUNY_BCC&amp;lang=en"><img class="book_cover" alt=" how to stop controlling others and start caring for yourself by Beattie, Melody." src="https://syndetics.com/index.php?client=primo&amp;isbn=1592857922/mc.jpg" /></a></span>  </div></li>
					            <li class="list-inline-item">  
					    <div class="views-field views-field-description">        <span class="field-content"><a href="https://suny-bcc.primo.exlibrisgroup.com/discovery/fulldisplay?docid=alma992265269904811&amp;context=U&amp;vid=01SUNY_BCC:01SUNY_BCC&amp;lang=en"><img class="book_cover" alt="Out of the Shadows Understanding Sexual Addiction by Carnes, Patrick J." src="https://syndetics.com/index.php?client=primo&amp;isbn=1592857698/mc.jpg" /></a></span>  </div></li>
					            <li class="list-inline-item">  
					    <div class="views-field views-field-description">        <span class="field-content"><a href="https://suny-bcc.primo.exlibrisgroup.com/discovery/fulldisplay?docid=alma992265269604811&amp;context=U&amp;vid=01SUNY_BCC:01SUNY_BCC&amp;lang=en"><img alt="Blank book cover" src="https://suny-bcc.primo.exlibrisgroup.com/discovery/custom/01SUNY_BCC-01SUNY_BCC/img/icon_book.png" /></a></span>  </div></li>
					        </ul></div> </div>
					
					<div class="more-link">
					  <a href="/library/new-books">
					    more new books  </a>
					</div>
				</div><!-- /region -->	
			</div><!-- /books-display -->
		
		<div id="news-wrapper" class="col-md-5">
			<div class="news-display list-group">
				<h3 class="block-title">News</h3>
				  <div class="views-row views-row-1 views-row-odd views-row-first list-group-item d-flex">
                      <div class="news-image-wrap col-2 p-1">  
                            <div class="fakeimg">Fake Image</div>
                       </div> <!-- /news-image-wrap -->
				      <div class="views-field views-field-title col">
                        <span class="field-content"><a href="/library/news/videos-pride-month-available-avon">Videos for PRIDE month available in AVON</a></span>  
                       </div>  <!-- /news-title -->
                   </div><!-- /list-group-item -->
				  
				  <div class="views-row views-row-2 views-row-even list-group-item d-flex">
                      <div class="news-image-wrap col-2 p-1">  
                            <div class="fakeimg">Fake Image</div>
                       </div> <!-- /news-image-wrap -->
				  <div class="views-field views-field-title col"><span class="field-content"><a href="/library/news/scholarly-research-tutorials">Scholarly Research Tutorials </a></span>  </div>  </div>
				 
				  <div class="views-row views-row-3 views-row-odd list-group-item">
				  <div class="views-field views-field-title "><span class="field-content"><a href="/library/news/updates-library-services-and-hours">Updates to Library Services and Hours</a></span>  </div>  </div>
				  
				  <div class="views-row views-row-4 views-row-even list-group-item">
				  <div class="views-field views-field-title"><span class="field-content"><a href="/library/news/message-library">A Message from the Library</a></span>  </div>  </div>
				  
				  <div class="views-row views-row-5 views-row-odd list-group-item">
				  <div class="views-field views-field-title"><span class="field-content"><a href="/library/news/jove-education-content-now-available">JoVE Education Content Now Available</a></span>  </div>  </div>
		
				  <div class="views-row views-row-6 views-row-even list-group-item">
				  <div class="views-field views-field-title"><span class="field-content"><a href="/library/news/mit-press-ebooks-now-available">MIT Press eBooks Now Available</a></span>  </div>  </div>
				
				  <div class="views-row views-row-7 views-row-odd list-group-item">
				  <div class="views-field views-field-title"><span class="field-content"><a href="/library/news/new-resource-national-emergency-library">New resource: National Emergency Library</a></span>  </div>  </div>
				  
				  <div class="views-row views-row-8 views-row-even views-row-last list-group-item">
				  <div class="views-field views-field-title"><span class="field-content"><a href="/library/news/sage-video-and-knowledge-databases-now-available">SAGE Video and Knowledge Databases Now Available</a></span>  </div></div>
				    
	
      
				<div class="more-link">
				  <a href="/library/news-and-events">
				    View older news  </a>
				</div>
			</div><!-- /news-display -->
		</div><!-- /news wrapper -->
	</div> <!-- /row -->
</div> <!-- /front-display -->
							
