
      <div class="firstnav">
            <nav class="navbar navbar-expand-xxl">
               <div class="container">
                   <div class="campus-logo">
                      <a class="navbar-brand" href="https://broome1.wpenginepowered.com/"><img src="/images/SB-Wordmark_Gold.png" alt="SUNY Broome Logo" height="27" width="250"></a> 
                   </div>
                  <button class="campusbutton navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#socnavbarSupportedContent" aria-controls="campuslinksNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
             <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-three-dots" viewBox="0 0 16 16">
              <path d="M3 9.5a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3m5 0a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3m5 0a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3"/>
            </svg>
             <span class="icon-text">campus</span>
                  </button>

            
                  <div class="collapse navbar-collapse justify-content-end" id="campuslinksNavDropdown">
                     <ul class="navbar-nav">
                        <li class="nav-item dropdown">
                           <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                           Campus Menu</a>
                           <ul class="dropdown-menu">
                              <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/academics-programs/">Academics &amp; Programs</a></li>
                              <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/admissions-costs/">Admissions &amp; Costs</a> </li>
                              <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/our-campus/">Our Campus</a></li>
                              <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/about/">About</a></li>
                              <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/careers-workforce/">Careers &amp; Workforce</a></li>
                              <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/community-alumni/">Foundation &amp; Alumni</a></li>
                           </ul>
                        </li>
                        <li class="nav-item"><a class="nav-link" href="https://broome1.wpenginepowered.com/directory/">Directory</a></li>
                        <li class="nav-item"><a class="nav-link" href="https://broome1.wpenginepowered.com/community-business/">Community &amp; Business</a></li>
                        <li class="nav-item dropdown">
                           <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                           Calendar</a>
                           <ul class="dropdown-menu">
                              <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/calendar/">Calendar</a> </li>
                              <li><a class="dropdown-item" href="https://news.sunybroome.edu/calendar/events/list/?tribe_eventcategory%5B0%5D=317">Academic Calendar</a></li>
                              <li><a class="dropdown-item" href="https://news.sunybroome.edu/calendar/events/">Events Calendar</a></li>
                              <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/registrar/college-academic-calendar/">Key Dates</a></li>
                           </ul>
                        </li>
                        <li class="nav-item dropdown">
                           <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                           News</a>
                           <ul class="dropdown-menu">
                              <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/news/">News</a> </li>
                              <li><a class="dropdown-item" href="https://news.sunybroome.edu/buzz/">Buzz</a></li>
                              <li><a class="dropdown-item" href="https://news.sunybroome.edu/buzz/category/hivehq/">HiveHQ</a></li>
                           </ul>
                        </li>
                        <li class="nav-item"><a class="nav-link" href="https://mycollege.sunybroome.edu">MyCollege</a></li>
                        <li class="nav-item"><a class="nav-link" href="https://broome1.wpenginepowered.com/community-alumni/give/">♥Give</a></li>
                     </ul>
                  </div><!-- /collapse -->
               </div><!-- /container -->
            </nav>
     </div><!-- /firstnav -->
