
      <div id="social-header">
         <div class="social-links ">
            <nav class="navbar bg-dark navbar-expand-xl" data-bs-theme="dark">
               <div class="container">

                    <div class="social-links-wrap">																														
                    <a class="px-1" href="https://facebook.com/sunybroome" title="Facebook" aria-label="Facebook" rel="noopener noreferrer" target="_blank" ><i class="bi bi-facebook"></i></a>
                    <a class="px-1"  href="https://twitter.com/sunybroome" title="Twitter" aria-label="Twitter" rel="noopener noreferrer" target="_blank"><i class="bi bi-twitter-x"></i></a>
                    <a class="px-1"  href="https://instagram.com/sunybroomecc" title="Instagram" aria-label="Instagram" rel="noopener noreferrer" target="_blank" ><i class="bi bi-instagram"></i></a>
                    <a class="px-1"  href="https://youtube.com/user/sunybroome" title="YouTube" aria-label="YouTube" rel="noopener noreferrer" target="_blank"><i class="bi bi-youtube"></i></a>
                    <a class="px-1" href="https://www.linkedin.com/school/sunybroome/" title="LinkedIn" aria-label="LinkedIn" rel="noopener noreferrer" target="_blank"><i class="bi bi-linkedin"></i></a>																					
                    </div> <!-- /social-links-wrap -->

                  <button class="campusbutton navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#campuslinksNavDropdown" aria-controls="campuslinksNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="icon material-icons-sharp">more_horiz</span>
                    <span class="icon-text">campus</span>
                  </button>

  
                  <div class="offcanvas offcanvas-end text-bg-dark" tabindex="-1" id="campuslinksNavDropdown" aria-controls="campuslinksNavDropdown">
                        <div class="offcanvas-header">
                          <h5 class="offcanvas-title" id="offcanvasNavbarDarkLabel">Campus Menu 1</h5>
                          <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                        </div><!-- /header -->
                    <div class="offcanvas-body">
                     <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                        <li class="nav-item"><a class="nav-link" href="https://broome1.wpenginepowered.com/directory/">Directory</a></li>
                        <li class="nav-item"><a class="nav-link" href="https://broome1.wpenginepowered.com/community-business/">Community &amp; Business</a></li>
                        <li class="nav-item dropdown">
                           <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                           Calendar</a>
                           <ul class="dropdown-menu">
                              <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/calendar/">Calendar</a> </li>
                              <li><a class="dropdown-item" href="https://news.sunybroome.edu/calendar/events/list/?tribe_eventcategory%5B0%5D=317">Academic Calendar</a></li>
                              <li><a class="dropdown-item" href="https://news.sunybroome.edu/calendar/events/">Events Calendar</a></li>
                              <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/registrar/college-academic-calendar/">Key Dates</a></li>
                           </ul>
                        </li>
                        <li class="nav-item dropdown">
                           <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                           News</a>
                           <ul class="dropdown-menu">
                              <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/news/">News</a> </li>
                              <li><a class="dropdown-item" href="https://news.sunybroome.edu/buzz/">Buzz</a></li>
                              <li><a class="dropdown-item" href="https://news.sunybroome.edu/buzz/category/hivehq/">HiveHQ</a></li>
                           </ul>
                        </li>
                        <li class="nav-item"><a class="nav-link" href="https://mycollege.sunybroome.edu">MyCollege</a></li>
                        <li class="nav-item"><a class="nav-link" href="https://broome1.wpenginepowered.com/community-alumni/give/">♥Give</a></li>
                     </ul>
                  </div><!-- /offcanvas body -->
               </div><!-- /offcanvas -->
            </nav>
   </div><!-- /social-links-->
      </div><!-- /social-header -->
