
      <div id="social-header">
         <div class="campus-links">
           
             <nav class="navbar bg-dark navbar-expand-lg" data-bs-theme="dark">
               <div class="container">
                   <div class="campus-logo">
                      <a class="navbar-brand" href="https://broome1.wpenginepowered.com/"><img src="/images/SB-Wordmark_Gold.png" alt="SUNY Broome Logo" height="27" width="250"></a> 
                   </div>
                  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#campuslinksNavDropdown" aria-controls="campuslinksNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                    <i class="bi bi-three-dots"></i>
                  </button>

            
                  <div class="collapse navbar-collapse justify-content-end" id="campuslinksNavDropdown">
                     <ul class="navbar-nav">
                        <li class="nav-item dropdown">
                           <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                           Campus Menu</a>
                           <ul class="dropdown-menu">
                              <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/academics-programs/">Academics &amp; Programs</a></li>
                              <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/admissions-costs/">Admissions &amp; Costs</a> </li>
                              <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/our-campus/">Our Campus</a></li>
                              <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/about/">About</a></li>
                              <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/careers-workforce/">Careers &amp; Workforce</a></li>
                              <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/community-alumni/">Foundation &amp; Alumni</a></li>
                           </ul>
                        </li>
                        <li class="nav-item"><a class="nav-link" href="https://broome1.wpenginepowered.com/directory/">Directory</a></li>
                        <li class="nav-item"><a class="nav-link" href="https://broome1.wpenginepowered.com/community-business/">Community &amp; Business</a></li>
                        <li class="nav-item dropdown">
                           <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                           Calendar</a>
                           <ul class="dropdown-menu">
                              <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/calendar/">Calendar</a> </li>
                              <li><a class="dropdown-item" href="https://news.sunybroome.edu/calendar/events/list/?tribe_eventcategory%5B0%5D=317">Academic Calendar</a></li>
                              <li><a class="dropdown-item" href="https://news.sunybroome.edu/calendar/events/">Events Calendar</a></li>
                              <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/registrar/college-academic-calendar/">Key Dates</a></li>
                           </ul>
                        </li>
                        <li class="nav-item dropdown">
                           <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                           News</a>
                           <ul class="dropdown-menu">
                              <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/news/">News</a> </li>
                              <li><a class="dropdown-item" href="https://news.sunybroome.edu/buzz/">Buzz</a></li>
                              <li><a class="dropdown-item" href="https://news.sunybroome.edu/buzz/category/hivehq/">HiveHQ</a></li>
                           </ul>
                        </li>
                        <li class="nav-item"><a class="nav-link" href="https://mycollege.sunybroome.edu">MyCollege</a></li>
                        <li class="nav-item"><a class="nav-link" href="https://broome1.wpenginepowered.com/community-alumni/give/">♥Give</a></li>
                     </ul>
                  </div><!-- /collapse -->
               </div><!-- /container -->
            </nav>
         </div><!-- /campus-links -->
      </div><!-- /social-header -->
