
      <div id="social-header">
         <div class="campus-links">
           
             <nav class="navbar bg-dark navbar-expand-lg" data-bs-theme="dark">
               <div class="container">
                   <div class="campus-logo">
                      <a class="navbar-brand" href="https://broome-bs1.ddev.site/"><img src="/images/SB-Wordmark_Gold.png" alt="SUNY Broome Logo" height="27" width="250"></a> 
                   </div>
                  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#campuslinksNavDropdown" aria-controls="campuslinksNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                  </button>

            
                  <div class="collapse navbar-collapse justify-content-end" id="campuslinksNavDropdown">
                     <ul class="navbar-nav">
                        <li class="nav-item dropdown">
                           <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                           Campus Menu</a>
                           <ul class="dropdown-menu">
                              <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/academics-programs/">Academics &amp; Programs</a></li>
                              <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/calendar/">Admissions &amp; Costs</a> </li>
                              <li><a class="dropdown-item" href="https://news.sunybroome.edu/calendar/events/">Our Campus</a></li>
                              <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/registrar/college-academic-calendar/">About</a></li>
                              <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/registrar/college-academic-calendar/">Careers &amp; Workforce</a></li>
                              <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/registrar/college-academic-calendar/">Foundation &amp; Alumni</a></li>
                           </ul>
                        </li>
                        <li class="nav-item"><a class="nav-link" href="https://broome-bs1.ddev.site/directory/">Directory</a></li>
                        <li class="nav-item"><a class="nav-link" href="https://broome-bs1.ddev.site/community-business/">Community &amp; Business</a></li>
                        <li class="nav-item dropdown">
                           <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                           Calendar</a>
                           <ul class="dropdown-menu">
                              <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/calendar/">Calendar</a> </li>
                              <li><a class="dropdown-item" href="https://news.sunybroome.edu/calendar/events/list/?tribe_eventcategory%5B0%5D=317">Academic Calendar</a></li>
                              <li><a class="dropdown-item" href="https://news.sunybroome.edu/calendar/events/">Events Calendar</a></li>
                              <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/registrar/college-academic-calendar/">Key Dates</a></li>
                           </ul>
                        </li>
                        <li class="nav-item dropdown">
                           <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                           News</a>
                           <ul class="dropdown-menu">
                              <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/news/">News</a> </li>
                              <li><a class="dropdown-item" href="https://news.sunybroome.edu/buzz/">Buzz</a></li>
                              <li><a class="dropdown-item" href="https://news.sunybroome.edu/buzz/category/hivehq/">HiveHQ</a></li>
                           </ul>
                        </li>
                        <li class="nav-item dropdown">
                           <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                           Login</a>
                           <ul class="dropdown-menu">
                              <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/login/">Login</a></li>
                              <li><a class="dropdown-item" href="https://mycollege.sunybroome.edu">MyCollege</a></li>
                              <li><a class="dropdown-item" href="https://broome-bs1.ddev.site/login/brightspace/">Brightspace</a></li>
                           </ul>
                        </li>
                        <li class="nav-item"><a class="nav-link" href="https://broome-bs1.ddev.site/community-alumni/give/">♥Give</a></li>
                     </ul>
                  </div>
                  <!-- /collapse -->
               </div>
    
               <!-- /container -->
            </nav>
         </div>
         <!-- /campus-links -->
      </div>
      <!-- /social-header -->
