<div class="secondnav">
<nav class="navbar campusnav bg-body-tertiary navbar-expand-xxl">
   <div class="container d-flex"">
      <div class="region region-branding">
         <a class="navbar-brand" href="https://sunybroome.edu"><img src="images/sunybroome-words_retina.png" alt="SUNY Broome Logo" height="27" width="250"></a> 
      </div>
      <!-- /class="region region-branding -->
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#campusNavDropdown" aria-controls="campusNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
         <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-list" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M2.5 12a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5m0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5m0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5"/>
         </svg>
         <span class="icon-text">campus</span>
      </button>
      <div class="collapse navbar-collapse justify-content-end" id="campusNavDropdown">
         <ul class="navbar-nav mr-auto mb-2 mb-lg-0">
            <!-- Mega Menu 1 -->
            <li class="nav-item dropdown dropdown-mega position-static">
               <a class="nav-link dropdown-toggle" href="https://broome1.wpenginepowered.com/academics-programs/" id="dropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">Academics &amp; Programs</a>
               <div class="dropdown-menu megamenu vw-100 start-50  translate-middle-x" aria-labelledby="dropdownMenuLink">
                  <div class="container">
                     <div class="row d-flex justify-content-center">
                        <div class="col-md-3 px-3">
                           <p>The best way to know if SUNY Broome is right for you is to come visit!</p>
                        </div>
                        <ul class="col-md-3 px-5">
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/academics-programs/programs-courses/">Programs &amp; Courses</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/academics-programs/programs-courses/our-programs/">Our Programs</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/academics-programs/programs-courses/our-courses/">Our Courses</a></li>
                           <li><a class="dropdown-item" href="https://catalog.sunybroome.edu/">College Catalog</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/ffec/">Fast Forward &amp; Early College</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/international/study-abroad/">Global Experiences (Study Abroad)</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/microcreds/">Microcredentials</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/academics-programs/programs-courses/non-credit-courses/">Non-Credit Courses</a></li>
                        </ul>
                        <ul class="col-md-3 px-5">
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/academics-programs/academic-divisions/">Academic Divisions</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/divisions/bps/">Business &amp; Professional Studies</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/divisions/hs/">Health Sciences</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/divisions/la/">Liberal Arts</a></li>
                           <li><a class="dropdown-item text-wrap" href="https://broome1.wpenginepowered.com/divisions/stem/">Science, Technology, Engineering &amp; Mathematics (STEM)</a></li>
                        </ul>
                        <ul class="col-md-3 px-5">
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/academics-programs/academic-resources/">Academic Resources</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/academicadvising/">Academic Advising</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/lad/">Learning Assistance Department</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/successcoaching/">Success Coaching</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/student-success-center-instructions/">Success Center Instructions</a></li>
                           <li><a class="dropdown-item" href="https://sunybroome.info/library/">Library</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/registrar/college-academic-calendar/">Academic Calendar</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/student-orientation/online-orientation/">Online Orientation</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/online/">Student Resources</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/eop/">Educational Opportunity Program (EOP)</a></li>
                        </ul>
                     </div>
                     <!--/row  -->
                  </div>
                  <!--/container red -->
               </div>
               <!-- Mega Menu 1 -->
            </li>
            <!-- Mega Menu 2 -->
            <li class="nav-item dropdown dropdown-mega position-static ">
               <a class="nav-link dropdown-toggle" href="https://broome1.wpenginepowered.com/admissions-costs/" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">Admissions &amp; Costs</a>
               <div class="dropdown-menu megamenu vw-100 start-50 translate-middle-x" aria-labelledby="dropdownMenuLink">
                  <div class="container">
                     <div class="row d-flex justify-content-center">
                        <ul class="col-md-3 px-4">
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/apply/">Apply to SUNY Broome</a>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/ffec/">Fast Forward &amp; Early College</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/student-orientation/">Orientation</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/ask-a-question/">Request More Information</a></li>
                           <li><a class="dropdown-item bigfat-menu" href="https://broome1.wpenginepowered.com/admissions-costs/parents-families/">Parents &amp; Families</a></li>
                        </ul>
                        <ul class="col-md-3 px-4">
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/admissions/">Admissions</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/admissions/admissions-requirements/">Admissions Requirements</a></li>
                           <li><a class="dropdown-item" href="http://connect.sunybroome.edu/portal/counselor">Admissions Counseling</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/admissions/inquire/">Ask a Question</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/admissions/enrollment-checklist/">Enrollment Checklist</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/admissions/admission-for-competitive-health-sciences-programs/">Competitive Admissions</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/international/">International Education</a></li>
                           <li><a class="dropdown-item" href="https://connect.sunybroome.edu/portal/groupvisits">Group Visits</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/admissions/suny-broome-on-the-move/">On the Move</a></li>
                        </ul>
                        <ul class="col-md-3 px-4">
                           <li><a class="dropdown-item" href="#awb-off-canvas-menu-trigger">Transfers</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/special-topics/transfer/">Transfer to SUNY Broome</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/transfer-planning/reverse-transfer/">Reverse Transfer</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/transfer-planning/bachelor-partnerships/">Bachelor Partnerships</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/transferagreements/">Transfer Agreements</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/transfer-planning/">Transfer Planning</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/admissions/broomes-suny-transfer-partnerships/">SUNY Transfer Partnerships</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/admissions/broome-2-binghamton-program/">Broome 2 Binghamton</a></li>
                        </ul>
                        <ul class="col-md-3 px-4">
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/admissions-costs/registration-payment/">Registration &amp; Payment</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/academicadvising/">Advising &amp; Registration</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/admissions-costs/registration-payment/course-registration-options/">Course Registration Options</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/financialaid/">Student Financial Services</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/registrar/">Registrar’s Office</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/financialaid/scholarships-grants-and-loans/">Scholarships, Grants and Loans</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/financialaid/student-accounts/">Student Accounts</a></li>
                        </ul>
                     </div>
                     <!--/row  -->
                  </div>
                  <!--/container-->
               </div>
               <!-- Mega Menu 2 -->
            </li>
            <!-- Mega Menu 3 -->
            <li class="nav-item dropdown dropdown-mega position-static ">
               <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" id="dropdownMenuLink" aria-expanded="false" href="https://broome1.wpenginepowered.com/our-campus/">Our Campus</a>
               <div class="dropdown-menu megamenu vw-100 start-50 translate-middle-x" aria-labelledby="dropdownMenuLink">
                  <div class="container">
                     <div class="row d-flex justify-content-center">
                        <ul class="col-md-3 px-4">
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/our-campus/student-activities-campus-life/">Student Activities &amp; Campus Life</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/housing/">Student Housing</a></li>
                           <li><a class="dropdown-item" href="https://broomehornets.com/landing/index">Athletics</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/special-topics/arts/">The Arts at SUNY Broome</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/dos/campus-life-office/">Campus Life Office</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/civic-engagement/">Civic Engagement</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/dos/">Dean of Students</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/diversity-inclusion/">Diversity &amp; Inclusion</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/icecenter/">Ice Center</a></li>
                           <li><a class="dropdown-item" href="https://sunybroome.campuslabs.com/engage/">The Swarm – Clubs &amp; Organizations</a></li>
                        </ul>
                        <ul class="col-md-3 px-4">
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/wellness/">Wellness</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/counseling/">Counseling Services</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/healthservices/">Health Services</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/safety/">Public Safety</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/titleix/">Title IX</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/financialaid/helpforhornets/">Help for Hornets</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/safety/policies-report/">Annual Safety and Security Report</a></li>
                        </ul>
                        <ul class="col-md-3 px-4">
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/our-campus/on-campus-services/">On-Campus Services</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/bccenter/">Child Care – The BC Center</a></li>
                           <li><a class="dropdown-item" href="https://sunybroome.bncollege.com/">Bookstore &amp; Campus Shop</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/our-campus/dining-at-suny-broome/">Campus Dining</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/fsa/">Faculty-Student Association</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/our-campus/on-campus-services/it-helpdesk/">IT/Helpdesk</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/veterans/">Veterans &amp; Military Affairs</a></li>
                        </ul>
                        <ul class="col-md-3 px-4">
                           <li><a class="dropdown-item" href="#awb-off-canvas-menu-trigger">Campus Policies &amp; Student Conduct</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/our-campus/academic-grievance-procedure/">Academic Grievance Procedure</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/osrr/student-code-of-conduct/">Student Code of Conduct</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/our-campus/complaints-grievances-appeals/">Student Complaints, Grievances, and Appeals</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/our-campus/civility-statement/">Civility Statement</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/wp-content/uploads/2025/03/Family-Education-Rights-and-Privacy-Act-FERPA.pdf">Educational Rights &amp; Privacy Act</a></li>
                           <li><a class="dropdown-item" href="#">Policies &amp; Prodecures</a></li>
                           <li><a class="dropdown-item" href="#">Student Handbook</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/wp-content/uploads/2025/03/4.4-Student-Rights-and-Responsibilities-Statement.pdf">Student Rights</a></li>
                        </ul>
                     </div>
                     <!--/row  -->
                  </div>
                  <!--/container-->
               </div>
               <!-- Mega Menu 3 -->
            </li>
            <!-- Mega Menu 4 -->
            <li class="nav-item dropdown dropdown-mega position-static ">
               <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" id="dropdownMenuLink" aria-expanded="false" href="https://broome1.wpenginepowered.com/about/">About</a>
               <div class="dropdown-menu megamenu vw-100 start-50 translate-middle-x" aria-labelledby="dropdownMenuLink">
                  <div class="container-fluid">
                     <div class="row d-flex justify-content-center">
                        <ul class="col-md-2 px-3">
                           <li><a class="dropdown-item" href="#">Our Institution</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/about/area-highlights/">Area Highlights</a></li>
                           <li><a class="dropdown-item" href="https://news.sunybroome.edu/buzz/">The Buzz – Campus News</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/about/college-history/">College History</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/about/directions-to-campus/">Directions to Campus</a></li>
                           <li><a class="dropdown-item" href="https://news.sunybroome.edu/calendar/events/">Events Calendar</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/about/on-campus-services/">On-Campus Services</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/housing/">Student Housing</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/about/map/">Parking and Campus Map</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/about/weather-related-closure-and-cancellation-procedure/">Weather-Related Closure and Cancellation Procedure</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/about/gatherings-and-assemblies-designated-public-areas/">Gatherings and Assemblies Designated Public Areas</a></li>
                        </ul>
                        <div class="col-md-2 px-3">
                           <ul class="mb-3">
                              <li><a class="dropdown-item" href="#">Our Vision &amp; Mission</a></li>
                              <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/about/vision/">Vision, Mission, Values and Institutional Learning Outcomes</a></li>
                              <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/wp-content/uploads/2025/03/Civility-Statement.pdf">Civility Statement</a></li>
                              <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/diversity-inclusion/">Diversity &amp; Inclusion</a></li>
                           </ul>
                           <ul>
                              <li><a class="dropdown-item" href="#">Our People &amp; Employment</a></li>
                              <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/shared-governance/chancellors-awards/">Chancellor’s Award Winners</a></li>
                              <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/about/employment/">Human Resources &amp; Employment</a></li>
                              <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/careercenter/student-employment-resources/">Student Employment Resources</a> </li>
                              <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/about/student-employment-job-posting-submission/">Student Employment Job Posting Submission</a></li>
                              <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/about/student-employment-vacancies/">Student Employment Vacancies</a></li>
                              <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/faculty-and-staff/spirit-award/">SUNY Broome Spirit Award</a></li>
                           </ul>
                        </div>
                        <ul class="col-md-2 px-3">
                           <li><a class="dropdown-item" href="#awb-off-canvas-menu-trigger">Information, Planning &amp; Reporting</a> </li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/about/annual-report/">Annual Report</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/about/consumer-information/">Consumer Information</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/about/fast-facts/">Enrollment Statistics (Fast Facts)</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/about/foil/">Freedom of Information Law (FOIL) Requests</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/ie/">Institutional Effectiveness</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/strategic-planning/">Strategic Planning</a></li>
                        </ul>
                        <ul class="col-md-2 px-3">
                           <li><a class="dropdown-item" href="#awb-off-canvas-menu-trigger">Governance &amp; Administration</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/bot/">Board of Trustees</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/about/office-of-the-president/">Office of The President</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/about/organizational-charts/">Organizational Charts</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/pp/">Policies &amp; Procedures</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/shared-governance/">Shared Governance</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/shared-governance/student-assembly/">Student Assembly</a></li>
                        </ul>
                        <ul class="col-md-2 px-3">
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/accessibility/">Accessibility</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/accessibility/digital-content/">Digital Content Accessibility</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/accessibility/classroom/">Classroom Accessibility</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/accessibility/web/">Web Accessibility</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/lad/aro/">Accessibility Resources</a></li>
                        </ul>
                     </div>
                     <!--/row  -->
                  </div>
                  <!--/container-->
               </div>
               <!-- Mega Menu 4 -->
            </li>
            <li class="nav-item dropdown">
               <a class="nav-link dropdown-toggle" href="https://broome1.wpenginepowered.com/careers-workforce/" id="dropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">Careers &amp; Workforce</a>
               <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                  <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/careers-workforce/conted/">Continuing Education</a></li>
                  <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/careers-workforce/workforce-development/">Workforce Development</a></li>
                  <li><a class="dropdown-item" href="https://ce.sunybroome.edu/">CE Course Catalog</a></li>
                  <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/careercenter/">Career Services</a></li>
                  <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/careercoach/">Career Coach</a> </li>
                  <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/conted/eac/">Entrepreneurship Assistance</a></li>
                  <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/careers-workforce/on-campus-jobs/">On-Campus Jobs</a></li>
                  <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/conted/suny-apprenticeship/">Apprenticeships</a></li>
               </ul>
            </li>
            <!-- Mega Menu 5 -->
            <li class="nav-item dropdown dropdown-mega position-static ">
               <a class="nav-link dropdown-toggle"  role="button" data-bs-toggle="dropdown" id="dropdownMenuLink" aria-expanded="false" href="https://broome1.wpenginepowered.com/community-alumni/">Foundation &amp; Alumni</a>
               <div class="dropdown-menu megamenu vw-100 start-50 translate-middle-x" aria-labelledby="dropdownMenuLink">
                  <div class="container">
                     <div class="row d-flex justify-content-center">
                        <ul class="col-md-4 px-5">
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/community-alumni/give/">♥Give</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/foundation/whygive/">Why Give</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/foundation/waystogive/">Ways To Give</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/foundation/fscampaign/">Faculty and Staff Giving Campaign</a></li>
                           <li><a class="dropdown-item bigfat-menu" href="https://broome1.wpenginepowered.com/community-alumni/suny-broome-scholarships/">SUNY Broome Scholarships</a></li>
                           <li><a class="dropdown-item bigfat-menu" href="https://broome1.wpenginepowered.com/community-alumni/vip-employee-appreciation-campaign/">VIP Employee Appreciation Campaign</a></li>
                        </ul>
                        <ul class="col-md-4 px-5">
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/foundation/alumni/">Alumni &amp; Friends</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/foundation/update-your-information/">Update Your Information</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/foundation/class-note-submission-form/">Class Note Submission Form</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/foundation/broome/">BROOME Magazine</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/foundation/benefits/">Alumni Benefits</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/community-alumni/alumni-features/">Alumni Features</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/foundation/alumnievent/">Alumni Events</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/registrar/transcripts/">Request Transcript</a></li>
                        </ul>
                        <ul class="col-md-4 px-5">
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/community-alumni/suny-broome-foundation/">SUNY Broome Foundation</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/foundation/about/">About the Foundation</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/foundation/foundationstaff/">Foundation Staff</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/foundation/foundationboard/">Foundation Board of Directors</a></li>
                           <li><a class="dropdown-item" href="https://broome1.wpenginepowered.com/foundation/foundationreport/">Foundation Annual Report</a></li>
                        </ul>
                     </div>
                     <!--/row  -->
                  </div>
                  <!--/container-->
               </div>
               <!-- Mega Menu 5 -->
               <!--   <li><a class="nav-link" href="https://broome1.wpenginepowered.com/apply/">Apply Now</a></li> -->
         </ul>
         <!-- /collapse -->
      </div>
      <!-- /container -->
</nav>
<!-- /campusnav -->
</div><!-- /secondnav -->

